# @package _global_

hydra:
  # run / sweep
  # Docs: https://hydra.cc/docs/configure_hydra/workdir/
  run:
    dir: ./outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ./outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}

  # job_logging
  # Docs: https://hydra.cc/docs/configure_hydra/logging/
  job_logging:
    formatters:
      simple:
        format: '[%(asctime)s][%(levelname)s] - %(message)s'

  job:
    chdir: True
