name: DiffusionModel
checkpoint: google/ddpm-bedroom-256
torch_dtype: float32
latent:
  shape:
    - 1
    - 3
    - 256
    - 256
scheduler:
  name: DDIMScheduler
  variance_type: fixed_small
unet:
  out_channels: 3
generate_kwargs:
  num_images_per_prompt: 1
  num_inference_steps: 100
  guidance_scale: 7.5
  eta: 1.0
